title: Bree B.
description: Bookmark this to keep an eye on my project updates!
baseurl: ""

nav:
  - name: Home
    url: /
  - name: About
    url: /About/
  - name: Projects
    url: /Projects/
  - name: Contact
    url: /Contact/

exclude:
  - README.md
